/**
 * X-Node AI Model Schema Registry
 *
 * Auto-generated from reverse-engineering https://dev-x-node.netlify.app/
 * (extracted from beautified Turbopack bundle, see xnode-bundle/output/).
 *
 * Each entry describes a netlify "model node" — UI is rendered by the
 * generic XNodeAIModelNode component, parameters are typed below.
 */

import type { XNodeMenuGroup, XNodeNodeCategory } from "./types";

export interface XNodeHandle {
  /** Internal handle id (e.g. "image", "text-negative", "lora-0"). */
  id: string;
  /** Data type carried by the handle. */
  type: string;
  /** Optional user-facing label rendered next to the handle. */
  label?: string;
}

export interface XNodeModelSchema {
  type: string;
  displayName: string;
  category: XNodeNodeCategory;
  menuGroup: XNodeMenuGroup;
  dimensions: { width: number; height: number };
  minimapColor?: string;
  inputs: XNodeHandle[];
  outputs: XNodeHandle[];
  defaultData: Record<string, unknown>;
  provider:
    | "gemini"
    | "openai"
    | "kie"
    | "fal"
    | "elevenlabs"
    | "xai"
    | "cloudinary"
    | "dropbox"
    | "internal";
}

export const X_NODE_MODELS: XNodeModelSchema[] = [
  {
    type: "lucy2",
    displayName: "Lucy 2",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 620 },
    minimapColor: "#7c3aed",
    inputs: [{"id": "image", "type": "image", "label": "Reference Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video", "label": "Recording"}],
    defaultData: {
      "portraitMode": false,
      "selectedCameraId": null,
      "connectionStatus": "idle",
      "error": null,
      "secondsUsed": 0,
      "outputVideo": null,
    },
    provider: "fal",
  },
  {
    type: "kling26",
    displayName: "KLING 2.6",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "inputImage": null,
      "endImage": null,
      "duration": "5s",
      "aspectRatio": "16:9",
      "negativePrompt": "",
      "generateAudio": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "kie",
  },
  {
    type: "klingVideo",
    displayName: "KLING 2.5 Turbo",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 480 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "startImage": null,
      "tailImage": null,
      "duration": "5s",
      "aspectRatio": "16:9",
      "negativePrompt": "",
      "cfgScale": 1,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "kie",
  },
  {
    type: "klingAvatar",
    displayName: "KLING Avatar v2",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 380 },
    inputs: [{"id": "image", "type": "image", "label": "Avatar"}, {"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "avatarImage": null,
      "audioFile": null,
      "inputPrompt": null,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "kie",
  },
  {
    type: "klingMotionControl",
    displayName: "KLING MotionControl",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "video", "type": "video", "label": "Reference Video"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "referenceImage": null,
      "referenceVideo": null,
      "characterOrientation": "video",
      "keepOriginalSound": true,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "kie",
  },
  {
    type: "wan25I2V",
    displayName: "Wan 2.5 Preview I2V",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "audio", "type": "audio", "label": "Audio"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "startImage": null,
      "audioFile": null,
      "duration": "5",
      "resolution": "720p",
      "negativePrompt": "",
      "promptExpansion": true,
      "seed": "void 0",
      "safetyChecker": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wan26I2V",
    displayName: "Wan 2.6 I2V Pro",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "mask", "type": "image", "label": "Mask"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "image": null,
      "audioFile": null,
      "duration": "5",
      "resolution": "720p",
      "negativePrompt": "",
      "promptExpansion": true,
      "multiShots": false,
      "seed": "void 0",
      "safetyChecker": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wan26R2V",
    displayName: "Wan 2.6 R2V Pro",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "video", "type": "video", "label": "Reference Videos"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "referenceVideo1": null,
      "referenceVideo2": null,
      "referenceVideo3": null,
      "aspectRatio": "16:9",
      "resolution": "720p",
      "duration": "5",
      "negativePrompt": "",
      "promptExpansion": true,
      "multiShots": false,
      "seed": "void 0",
      "safetyChecker": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wan22A14BLora",
    displayName: "Wan 2.2 A14B LoRA",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 500 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Neg. Prompt"}, {"id": "image-end", "type": "image", "label": "End Image"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "inputImage": null,
      "endImageUrl": null,
      "negativePrompt": "",
      "numFrames": 81,
      "framesPerSecond": 30,
      "resolution": "720p",
      "aspectRatio": "auto",
      "numInferenceSteps": 27,
      "enableSafetyChecker": false,
      "enableOutputSafetyChecker": false,
      "enablePromptExpansion": false,
      "acceleration": "regular",
      "guidanceScale": 3.5,
      "guidanceScale2": 4,
      "shift": 5,
      "interpolatorModel": "film",
      "numInterpolatedFrames": 1,
      "adjustFpsForInterpolation": true,
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "seed": "void 0",
      "reverseVideo": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wan22VaceA14b",
    displayName: "Wan 2.2 VACE A14B",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 500 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Neg. Prompt"}, {"id": "video", "type": "video", "label": "Source Video"}, {"id": "video-mask", "type": "video", "label": "Mask Video"}, {"id": "image-mask", "type": "image", "label": "Mask Image"}, {"id": "image-ref-0", "type": "image", "label": "Ref Image 1"}, {"id": "image-ref-1", "type": "image", "label": "Ref Image 2"}, {"id": "image-first", "type": "image", "label": "First Frame"}, {"id": "image-last", "type": "image", "label": "Last Frame"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "inpaint",
      "inputPrompt": null,
      "negativePrompt": "letterboxing, borders, black bars, text, subtitles, watermark, logo",
      "videoUrl": null,
      "maskVideoUrl": null,
      "maskImageUrl": null,
      "matchInputNumFrames": false,
      "numFrames": 81,
      "matchInputFramesPerSecond": false,
      "framesPerSecond": 16,
      "resolution": "auto",
      "aspectRatio": "auto",
      "numInferenceSteps": 30,
      "guidanceScale": 5,
      "sampler": "unipc",
      "shift": 5,
      "seed": "void 0",
      "acceleration": "regular",
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "enableSafetyChecker": false,
      "enablePromptExpansion": false,
      "preprocess": false,
      "numInterpolatedFrames": 0,
      "temporalDownsampleFactor": 0,
      "enableAutoDownsample": false,
      "autoDownsampleMinFps": 15,
      "interpolatorModel": "film",
      "transparencyMode": "content_aware",
      "returnFramesZip": false,
      "syncMode": true,
      "expandLeft": true,
      "expandRight": true,
      "expandTop": true,
      "expandBottom": true,
      "expandRatio": 0.25,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wanAnimateReplace",
    displayName: "Wan 2.2 Animate Replace",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 400 },
    inputs: [{"id": "video", "type": "video", "label": "Source Video"}, {"id": "characterImage", "type": "image", "label": "Character"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "sourceVideo": null,
      "characterImage": null,
      "resolution": "720p",
      "guidanceScale": 5,
      "shift": 5,
      "useTurbo": true,
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "numInferenceSteps": 30,
      "enableSafetyChecker": false,
      "enableOutputSafetyChecker": false,
      "seed": "void 0",
      "returnFramesZip": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wanAnimateMove",
    displayName: "Wan 2.2 Animate Move",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 400 },
    inputs: [{"id": "video", "type": "video", "label": "Motion Video"}, {"id": "image", "type": "image", "label": "Character"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "moveVideo": null,
      "moveImage": null,
      "moveBackground": null,
      "resolution": "720p",
      "guidanceScale": 5,
      "shift": 5,
      "useTurbo": true,
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "numInferenceSteps": 30,
      "enableSafetyChecker": false,
      "enableOutputSafetyChecker": false,
      "seed": "void 0",
      "returnFramesZip": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wanMotion",
    displayName: "Wan Motion",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 420 },
    inputs: [{"id": "video", "type": "video", "label": "Driving Video"}, {"id": "image", "type": "image", "label": "Reference Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "driveVideo": null,
      "startImage": null,
      "inputPrompt": "",
      "acceleration": "regular",
      "adaptMotion": true,
      "enhanceIdentity": false,
      "enableSafetyChecker": false,
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "wanVisionEnhancer",
    displayName: "Wan Vision Enhancer",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 380 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "video": null,
      "targetResolution": "1080p",
      "creativity": 0.1,
      "inputPrompt": null,
      "negativePrompt": "",
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "videoUnderstanding",
    displayName: "Video Understanding",
    category: "text",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 300 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "text", "type": "text"}],
    defaultData: {
      "inputPrompt": null,
      "detailedAnalysis": false,
      "outputText": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "seedVRUpscale",
    displayName: "SeedVR2 Upscale",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 380 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "image", "type": "image"}, {"id": "video", "type": "video"}],
    defaultData: {
      "inputMode": "image",
      "image": null,
      "video": null,
      "upscaleMode": "factor",
      "upscaleFactor": 2,
      "targetResolution": "1080p",
      "noiseScale": 0.1,
      "outputFormat": "X264 (.mp4)",
      "imageOutputFormat": "jpg",
      "outputQuality": "high",
      "outputWriteMode": "balanced",
      "syncMode": true,
      "seed": "void 0",
      "outputVideo": null,
      "outputImage": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "topazVideoUpscale",
    displayName: "Topaz Video Upscale",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 420 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "video": null,
      "model": "Proteus",
      "upscaleFactor": 2,
      "targetFps": "void 0",
      "compression": 0,
      "noise": 0,
      "halo": 0,
      "grain": 0,
      "recoverDetail": 0,
      "h264Output": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "autoSubtitle",
    displayName: "Auto Subtitle",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 700 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "videoFile": null,
      "language": "en",
      "fontName": "Montserrat",
      "fontSize": 100,
      "fontWeight": "bold",
      "fontColor": "white",
      "highlightColor": "purple",
      "backgroundColor": "none",
      "position": "bottom",
      "yOffset": 75,
      "wordsPerSubtitle": 3,
      "enableAnimation": true,
      "strokeWidth": 3,
      "strokeColor": "black",
      "backgroundOpacity": 0.8,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falMergeVideos",
    displayName: "Merge Videos",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 500 },
    inputs: [{"id": "video-1", "type": "video", "label": "Video 1"}, {"id": "video-2", "type": "video", "label": "Video 2"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "videoInputCount": 2,
      "targetFps": null,
      "resolution": "none",
      "customWidth": 1024,
      "customHeight": 1024,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falBlendVideo",
    displayName: "Blend Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 460 },
    inputs: [{"id": "top-video", "type": "video", "label": "Top"}, {"id": "bottom-video", "type": "video", "label": "Bottom"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "blendMode": "overlay",
      "opacity": 1,
      "shortest": true,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falMergeAudioVideo",
    displayName: "Merge Audio & Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 350 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}, {"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "startOffset": 0,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "reverseVideo",
    displayName: "Reverse Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 320 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "trimVideo",
    displayName: "Trim Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 390 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "startTime": 1,
      "endTime": null,
      "duration": 2,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "veoVideo",
    displayName: "VEO Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 550 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image", "type": "image", "label": "First Frame"}, {"id": "lastFrame", "type": "image", "label": "Last Frame"}, {"id": "ref-image-1", "type": "image", "label": "Reference 1"}, {"id": "ref-image-2", "type": "image", "label": "Reference 2"}, {"id": "ref-image-3", "type": "image", "label": "Reference 3"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "text-to-video",
      "inputPrompt": null,
      "inputImage": null,
      "lastFrame": null,
      "referenceImages": [],
      "model": "veo-3.1-fast-generate-preview",
      "aspectRatio": "16:9",
      "resolution": "720p",
      "durationSeconds": "4",
      "personGeneration": "allow_all",
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
      "videoHistory": [],
      "selectedVideoHistoryIndex": 0,
    },
    provider: "kie",
  },
  {
    type: "ltx23",
    displayName: "LTX 2.3",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 520 },
    inputs: [{"id": "audio", "type": "audio", "label": "Audio"}, {"id": "image", "type": "image", "label": "Image"}, {"id": "image-end", "type": "image", "label": "End Frame"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "audio-to-video",
      "guidanceScale": 5,
      "aspectRatio": "16:9",
      "resolution": "1080p",
      "duration": 6,
      "fps": 25,
      "generateAudio": true,
      "inputPrompt": null,
      "inputAudio": null,
      "inputImage": null,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "ltx219bV2V",
    displayName: "LTX 2.19b V2V",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 580 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "image", "type": "image", "label": "First Frame"}, {"id": "image-last", "type": "image", "label": "End Frame"}, {"id": "audio", "type": "audio", "label": "Audio"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "inputPrompt": null,
      "syncMode": true,
      "enableSafetyChecker": false,
      "matchVideoLength": true,
      "numFrames": 121,
      "negativePrompt": "",
      "guidanceScale": 3,
      "numInferenceSteps": 40,
      "acceleration": "regular",
      "videoSize": "auto",
      "generateAudio": true,
      "useMultiscale": true,
      "matchInputFps": true,
      "fps": 25,
      "cameraLora": "none",
      "cameraLoraScale": 1,
      "preprocessor": "none",
      "icLora": "match_preprocessor",
      "icLoraScale": 1,
      "imageStrength": 1,
      "endImageStrength": 1,
      "videoStrength": 1,
      "audioStrength": 1,
      "enablePromptExpansion": true,
      "videoOutputType": "X264 (.mp4)",
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "ltx2322bDistilled",
    displayName: "LTX 2.3 22B Distilled LoRA",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 580 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "image", "type": "image", "label": "First Frame"}, {"id": "image-last", "type": "image", "label": "End Frame"}, {"id": "audio", "type": "audio", "label": "Audio"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "reference-video-to-video",
      "inputPrompt": null,
      "syncMode": true,
      "enableSafetyChecker": false,
      "matchVideoLength": true,
      "numFrames": 121,
      "negativePrompt": "",
      "guidanceScale": 3,
      "numInferenceSteps": 40,
      "acceleration": "regular",
      "videoSize": "auto",
      "generateAudio": true,
      "useMultiscale": true,
      "matchInputFps": true,
      "fps": 24,
      "scheduler": "ltx2",
      "cameraLora": "none",
      "cameraLoraScale": 1,
      "preprocessor": "none",
      "icLoraType": "union",
      "icLoraScale": 1,
      "distillLoraSecondPassScale": 0.5,
      "imageStrength": 1,
      "endImageStrength": 1,
      "videoStrength": 1,
      "audioStrength": 1,
      "enablePromptExpansion": true,
      "videoOutputType": "X264 (.mp4)",
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "ltx2322b",
    displayName: "LTX 2.3 22b LoRA",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 580 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "image", "type": "image", "label": "First Frame"}, {"id": "image-last", "type": "image", "label": "End Frame"}, {"id": "audio", "type": "audio", "label": "Audio"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "reference-video-to-video",
      "inputPrompt": null,
      "syncMode": true,
      "enableSafetyChecker": false,
      "matchVideoLength": true,
      "numFrames": 121,
      "negativePrompt": "",
      "numInferenceSteps": 40,
      "acceleration": "regular",
      "videoSize": "auto",
      "generateAudio": true,
      "useMultiscale": true,
      "matchInputFps": true,
      "fps": 24,
      "scheduler": "ltx2",
      "cameraLora": "none",
      "cameraLoraScale": 1,
      "preprocessor": "none",
      "icLoraType": "union",
      "icLoraScale": 1,
      "videoCfgScale": 3,
      "videoStgScale": "void 0",
      "videoRescalingScale": 0.7,
      "videoModalityScale": 3,
      "audioCfgScale": 7,
      "audioStgScale": "void 0",
      "audioRescalingScale": 0.7,
      "audioModalityScale": 3,
      "gradientEstimationGamma": 2,
      "useRestartSampling": false,
      "distillLoraFirstPassScale": 0.2,
      "distillLoraSecondPassScale": 0.5,
      "videoStrength": 1,
      "audioStrength": 1,
      "enablePromptExpansion": true,
      "videoOutputType": "X264 (.mp4)",
      "videoQuality": "high",
      "videoWriteMode": "balanced",
      "seed": "void 0",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "sam3SegmentVideo",
    displayName: "SAM-3 Segment Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 420, height: 680 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "prompt": "",
      "point_prompts": [],
      "apply_mask": false,
      "detection_threshold": 0.5,
      "assumedFps": 30,
      "currentFrameIndex": 0,
      "currentObjectId": 1,
      "drawingMode": "point_fg",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "sam31SegmentVideo",
    displayName: "SAM-3.1 Segment Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 420, height: 720 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "prompt": "",
      "point_prompts": [],
      "box_prompts": [],
      "apply_mask": true,
      "detection_threshold": 0.5,
      "max_num_objects": 16,
      "video_output_type": "X264 (.mp4)",
      "assumedFps": 30,
      "currentFrameIndex": 0,
      "currentObjectId": 1,
      "drawingMode": "point_fg",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "seedance20",
    displayName: "Seedance 2.0",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 660 },
    inputs: [{"id": "image", "type": "image", "label": "Image 1"}, {"id": "image-1", "type": "image", "label": "Image 2"}, {"id": "image-2", "type": "image", "label": "Image 3"}, {"id": "image-3", "type": "image", "label": "Image 4"}, {"id": "image-4", "type": "image", "label": "Image 5"}, {"id": "image-5", "type": "image", "label": "Image 6"}, {"id": "image-6", "type": "image", "label": "Image 7"}, {"id": "image-7", "type": "image", "label": "Image 8"}, {"id": "image-8", "type": "image", "label": "Image 9"}, {"id": "video", "type": "video", "label": "Video 1"}, {"id": "video-1", "type": "video", "label": "Video 2"}, {"id": "video-2", "type": "video", "label": "Video 3"}, {"id": "audio", "type": "audio", "label": "Audio 1"}, {"id": "audio-1", "type": "audio", "label": "Audio 2"}, {"id": "audio-2", "type": "audio", "label": "Audio 3"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "omni",
      "aspectRatio": "16:9",
      "quality": "high",
      "duration": 5,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "happyHorse",
    displayName: "Muapi - HappyHorse",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 420 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "aspectRatio": "16:9",
      "duration": 5,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falHappyHorse",
    displayName: "Fal - HappyHorse",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 560 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "referenceToVideo",
      "imageInputCount": 9,
      "aspectRatio": "16:9",
      "resolution": "1080p",
      "duration": 5,
      "seed": null,
      "enableSafetyChecker": false,
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falSmartResize",
    displayName: "Fal - Smart Resize",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 500 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt (optional)"}, {"id": "image", "type": "image", "label": "Image"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {
      "targetWidth": 1024,
      "targetHeight": 1024,
      "resolution": "1K",
      "outputFormat": "png",
      "safetyTolerance": "4",
      "seed": null,
      "syncMode": false,
      "outputImage": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "generateTTS",
    displayName: "Speech (TTS)",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 380 },
    inputs: [{"id": "text", "type": "text", "label": "Text"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "inputPrompt": null,
      "outputAudio": null,
      "selectedVoice": {},
      "name": "Custom Voice",
    },
    provider: "elevenlabs",
  },
  {
    type: "voiceChanger",
    displayName: "Voice Changer",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 320 },
    inputs: [{"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "inputAudio": null,
      "outputAudio": null,
      "selectedVoice": {},
      "name": "Custom Voice",
    },
    provider: "elevenlabs",
  },
  {
    type: "voiceIsolator",
    displayName: "Voice Isolator",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 200 },
    inputs: [{"id": "audio", "type": "audio", "label": "Audio"}, {"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "inputAudio": null,
      "outputAudio": null,
      "status": "idle",
      "error": null,
    },
    provider: "elevenlabs",
  },
  {
    type: "soundEffect",
    displayName: "Sound Effect",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 180 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "inputPrompt": null,
      "outputAudio": null,
      "durationSeconds": null,
      "promptInfluence": 0.3,
      "loop": false,
      "status": "idle",
      "error": null,
    },
    provider: "elevenlabs",
  },
  {
    type: "falMergeAudios",
    displayName: "Merge Audios",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 350 },
    inputs: [{"id": "audio-1", "type": "audio", "label": "Audio 1"}, {"id": "audio-2", "type": "audio", "label": "Audio 2"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "audioInputCount": 2,
      "outputFormat": "void 0",
      "outputAudio": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "generateTTSStitch",
    displayName: "TTS Stitch",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 580 },
    inputs: [{"id": "text", "type": "text", "label": "Text Segments"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "outputAudio": null,
      "selectedVoice": {},
      "name": "Custom Voice",
    },
    provider: "elevenlabs",
  },
  {
    type: "dubbing",
    displayName: "Dubbing",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 300 },
    inputs: [{"id": "audio", "type": "audio", "label": "Audio"}, {"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "audio", "type": "audio"}],
    defaultData: {
      "inputMedia": null,
      "outputAudio": null,
      "sourceLang": "auto",
      "targetLang": "it",
      "numSpeakers": 0,
      "dropBackgroundAudio": false,
      "disableVoiceCloning": false,
      "status": "idle",
      "error": null,
    },
    provider: "elevenlabs",
  },
  {
    type: "xaiSpeechToText",
    displayName: "xAI Speech to Text",
    category: "audio",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 420 },
    inputs: [{"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [{"id": "text", "type": "text"}, {"id": "words", "type": "text"}],
    defaultData: {
      "audioUrl": "",
      "language": "auto",
      "diarize": false,
      "format": true,
      "multichannel": false,
      "outputText": null,
      "outputWords": null,
      "detectedLanguage": null,
      "duration": null,
      "wordCount": null,
      "status": "idle",
      "error": null,
    },
    provider: "xai",
  },
  {
    type: "extractFrames",
    displayName: "Fal Frame Extract",
    category: "utility",
    menuGroup: "Utility",
    dimensions: { width: 300, height: 340 },
    inputs: [{"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "dwPose",
    displayName: "DWPose",
    category: "utility",
    menuGroup: "Utility",
    dimensions: { width: 300, height: 380 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "qwenMultipleAngles",
    displayName: "Qwen Multiple Angles",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 380, height: 600 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "qwenImageEditInpaint",
    displayName: "Qwen Image Edit Inpaint",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 900 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "mask", "type": "image", "label": "Mask"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "qwenImageEdit2511Lora",
    displayName: "Qwen 2511 Image Edit LoRA",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 680 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image", "type": "image", "label": "Image 1"}, {"id": "image-1", "type": "image", "label": "Image 2"}, {"id": "image-2", "type": "image", "label": "Image 3"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}, {"id": "text-negative", "type": "text", "label": "Neg. Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "qwenImage2512Lora",
    displayName: "Qwen 2512 T2I LoRA",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 600 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Neg. Prompt"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "qwenImage2ProEdit",
    displayName: "Qwen Image 2 Pro Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 860 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image", "type": "image", "label": "Image 1"}, {"id": "image-1", "type": "image", "label": "Image 2"}, {"id": "image-2", "type": "image", "label": "Image 3"}, {"id": "image-3", "type": "image", "label": "Image 4"}, {"id": "image-4", "type": "image", "label": "Image 5"}, {"id": "image-5", "type": "image", "label": "Image 6"}, {"id": "text-negative", "type": "text", "label": "Neg. Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "zImageTurboI2I",
    displayName: "Z-Image Turbo I2I",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 580 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "zImageTurboLora",
    displayName: "Z-Image Turbo LoRA",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 640 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "zImageTurboInpaintLora",
    displayName: "Z-Image Turbo Inpaint",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 740 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "image-1", "type": "image", "label": "Mask"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "grokImagine",
    displayName: "Grok Imagine Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 450 },
    inputs: [{"id": "image", "type": "image", "label": "Image 1"}, {"id": "image-2", "type": "image", "label": "Image 2"}, {"id": "image-3", "type": "image", "label": "Image 3"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "xai",
  },
  {
    type: "grokVideo",
    displayName: "Grok Video",
    category: "video",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 480 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image", "type": "image", "label": "Image"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "ref-image-1", "type": "image", "label": "Ref 1"}, {"id": "ref-image-2", "type": "image", "label": "Ref 2"}, {"id": "ref-image-3", "type": "image", "label": "Ref 3"}, {"id": "ref-image-4", "type": "image", "label": "Ref 4"}, {"id": "ref-image-5", "type": "image", "label": "Ref 5"}, {"id": "ref-image-6", "type": "image", "label": "Ref 6"}, {"id": "ref-image-7", "type": "image", "label": "Ref 7"}],
    outputs: [{"id": "video", "type": "video"}],
    defaultData: {
      "mode": "image-to-video",
      "inputPrompt": null,
      "inputImage": null,
      "inputVideo": null,
      "referenceImages": [],
      "duration": 6,
      "aspectRatio": "auto",
      "resolution": "720p",
      "outputVideo": null,
      "status": "idle",
      "error": null,
    },
    provider: "xai",
  },
  {
    type: "klingO1",
    displayName: "KLING-Images-O1",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 520 },
    inputs: [{"id": "image", "type": "image", "label": "Reference Images"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "kie",
  },
  {
    type: "seedreamV45Edit",
    displayName: "Seedream 4.5 Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 800 },
    inputs: [{"id": "image", "type": "image", "label": "Images"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "seedreamV5LiteEdit",
    displayName: "Seedream v5.0 Lite Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 360, height: 800 },
    inputs: [{"id": "image", "type": "image", "label": "Images"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "fluxProKontextEdit",
    displayName: "Flux-Pro Kontext Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 640 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "phota",
    displayName: "Phota",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 860 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image-1", "type": "image", "label": "Image 1"}, {"id": "profile-id-1", "type": "text", "label": "Profile 1"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "flux2Klein9BBaseLora",
    displayName: "Flux 2 Klein 9B LoRA",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 640 },
    inputs: [{"id": "image", "type": "image", "label": "Image 1"}, {"id": "image-1", "type": "image", "label": "Image 2"}, {"id": "image-2", "type": "image", "label": "Image 3"}, {"id": "image-3", "type": "image", "label": "Image 4"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "text-negative", "type": "text", "label": "Negative Prompt"}, {"id": "lora-0", "type": "lora", "label": "LoRA 1"}, {"id": "lora-1", "type": "lora", "label": "LoRA 2"}, {"id": "lora-2", "type": "lora", "label": "LoRA 3"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "aiFaceSwap",
    displayName: "AI Face Swap (Muapi)",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 420 },
    inputs: [{"id": "image", "type": "image", "label": "Face Image"}, {"id": "video", "type": "video", "label": "Target Video"}],
    outputs: [{"id": "video", "type": "video"}, {"id": "image", "type": "image"}],
    defaultData: {},
    provider: "fal",
  },
  {
    type: "falHyWuEdit",
    displayName: "Hy-Wu Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 680 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image-1", "type": "image", "label": "Image 1"}, {"id": "image-2", "type": "image", "label": "Image 2"}, {"id": "image-3", "type": "image", "label": "Image 3"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {
      "imageSizePreset": "auto",
      "customWidth": 1024,
      "customHeight": 1024,
      "numInferenceSteps": 30,
      "numImages": 1,
      "seed": null,
      "enableThinking": true,
      "enableSafetyChecker": false,
      "outputFormat": "png",
      "syncMode": true,
      "outputImage": null,
      "outputImages": [],
      "selectedOutputIndex": 0,
      "imageHistory": [],
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falPixelcutBgRemoval",
    displayName: "PixelCut BG Removal",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 320, height: 440 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {
      "outputFormat": "rgba",
      "syncMode": true,
      "outputImage": null,
      "outputFile": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "falGptImage2Edit",
    displayName: "FAL GPT-2 Image Edit",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 850 },
    inputs: [{"id": "text", "type": "text", "label": "Prompt"}, {"id": "image-1", "type": "image", "label": "Image 1"}, {"id": "image-2", "type": "image", "label": "Image 2"}, {"id": "image-3", "type": "image", "label": "Image 3"}, {"id": "image-4", "type": "image", "label": "Image 4"}, {"id": "image-5", "type": "image", "label": "Image 5"}, {"id": "image-6", "type": "image", "label": "Image 6"}, {"id": "image-7", "type": "image", "label": "Image 7"}, {"id": "image-8", "type": "image", "label": "Image 8"}, {"id": "image-9", "type": "image", "label": "Image 9"}, {"id": "mask", "type": "image", "label": "Mask"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {
      "imageSizePreset": "auto",
      "customWidth": 1024,
      "customHeight": 1024,
      "quality": "high",
      "numImages": 1,
      "outputFormat": "png",
      "syncMode": true,
      "outputImage": null,
      "outputImages": [],
      "selectedOutputIndex": 0,
      "imageHistory": [],
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "openaiImage",
    displayName: "OpenAI Image",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 340, height: 640 },
    inputs: [{"id": "image", "type": "image", "label": "Images"}, {"id": "image-mask", "type": "image", "label": "Mask"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "image", "type": "image"}],
    defaultData: {},
    provider: "openai",
  },
  {
    type: "falTextOutput",
    displayName: "Fal Text Output",
    category: "text",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 280 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}],
    outputs: [{"id": "text", "type": "text"}],
    defaultData: {
      "outputText": null,
      "selectedModel": "void 0",
      "parameters": {},
    },
    provider: "fal",
  },
  {
    type: "dynamicFal",
    displayName: "FAL Model",
    category: "generation",
    menuGroup: "Generate",
    dimensions: { width: 300, height: 280 },
    inputs: [{"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Prompt"}, {"id": "audio", "type": "audio", "label": "Audio"}, {"id": "video", "type": "video", "label": "Video"}],
    outputs: [{"id": "image", "type": "image"}, {"id": "video", "type": "video"}, {"id": "audio", "type": "audio"}, {"id": "text", "type": "text"}],
    defaultData: {
      "selectedModel": "void 0",
      "outputType": "image",
      "parameters": {},
    },
    provider: "fal",
  },
  {
    type: "dropboxUpload",
    displayName: "Dropbox Upload",
    category: "utility",
    menuGroup: "Network",
    dimensions: { width: 280, height: 330 },
    minimapColor: "#06b6d4",
    inputs: [{"id": "input", "type": "file", "label": "Input"}],
    outputs: [{"id": "output", "type": "file", "label": "Output"}],
    defaultData: {
      "folderPath": "/node-banana",
      "fileName": "",
      "uploadedUrl": null,
      "uploadedPath": null,
      "uploadedContentType": null,
      "uploadedSize": null,
      "status": "idle",
      "error": null,
    },
    provider: "dropbox",
  },
  {
    type: "cloudinaryUpload",
    displayName: "Cloudinary Upload",
    category: "utility",
    menuGroup: "Network",
    dimensions: { width: 300, height: 380 },
    minimapColor: "#0ea5e9",
    inputs: [{"id": "input", "type": "file", "label": "Input"}],
    outputs: [{"id": "output", "type": "file", "label": "Output"}],
    defaultData: {
      "cloudName": "",
      "apiKey": "",
      "fileName": "",
      "uploadedUrl": null,
      "uploadedPublicId": null,
      "uploadedResourceType": null,
      "uploadedContentType": null,
      "uploadedSize": null,
      "status": "idle",
      "error": null,
    },
    provider: "cloudinary",
  },
  {
    type: "webhookTrigger",
    displayName: "Webhook Trigger",
    category: "utility",
    menuGroup: "Network",
    dimensions: { width: 300, height: 420 },
    minimapColor: "#06b6d4",
    inputs: [],
    outputs: [{"id": "image", "type": "text"}, {"id": "text", "type": "Text"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "audio", "type": "audio", "label": "Audio"}],
    defaultData: {
      "slug": "",
      "autoRun": true,
      "isPublished": false,
      "webhookToken": null,
      "outputImages": "Array(10).fill(null)",
      "outputText": null,
      "outputVideo": null,
      "outputAudio": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "webhookResponse",
    displayName: "Webhook Response",
    category: "utility",
    menuGroup: "Network",
    dimensions: { width: 260, height: 280 },
    minimapColor: "#06b6d4",
    inputs: [{"id": "input", "type": "file", "label": "Input"}, {"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Text"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [],
    defaultData: {
      "collectedImage": null,
      "collectedText": null,
      "collectedVideo": null,
      "collectedAudio": null,
      "collectedImages": [],
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
  {
    type: "dataForward",
    displayName: "Data Forward",
    category: "utility",
    menuGroup: "Network",
    dimensions: { width: 280, height: 400 },
    minimapColor: "#ec4899",
    inputs: [{"id": "input", "type": "file", "label": "Input"}, {"id": "image", "type": "image", "label": "Image"}, {"id": "text", "type": "text", "label": "Text"}, {"id": "video", "type": "video", "label": "Video"}, {"id": "audio", "type": "audio", "label": "Audio"}],
    outputs: [],
    defaultData: {
      "webhookUrl": "",
      "authHeader": "void 0",
      "collectedImage": null,
      "collectedText": null,
      "collectedVideo": null,
      "collectedAudio": null,
      "collectedImages": [],
      "lastResponse": null,
      "lastStatus": null,
      "status": "idle",
      "error": null,
    },
    provider: "fal",
  },
]

export function getXNodeModel(type: string): XNodeModelSchema | undefined {
  return X_NODE_MODELS.find((m) => m.type === type);
}
